name: Pull Request to Main branch

on:
  pull_request:
    branches:
      - main

concurrency:
  group: terraform-state
    
jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out code
        uses: actions/checkout@v3 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        env:
            TF_VAR_rollbar_api_key: ${{ secrets.ROLLBAR_API_KEY }}
            TF_VAR_slack_service_account_id: ${{ secrets.SLACK_SERVICE_ACCOUNT_ID }}
        run: terraform plan
        continue-on-error: true

      - name: Fail if plan has failed
        if: steps.plan.outputs.exitcode == 1
        run: exit 1